### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by aikedejongste** [otwieracz/backuppc_exporter#4]
Could you add license file? I'd like to package this into a deb-package for Debian/Ubuntu, but then it needs a license. My preference would be a BSD 2-clause: https://opensource.org/licenses/bsd-license.php

```
Could not determine license for "github.com/otwieracz/backuppc_exporter": GET https://api.github.com/repos/otwieracz/backuppc_exporter/license: 404 Not Found []
```

**Comment by otwieracz** [comment]
License added.
